### ISSUE TITLE
'max_length' is ignored when used with IntegerField

### ISSUE THREAD

**Issue by Lightyagami1** [shashi1920/collectionNvalidation#1]
WARNINGS:
collection.ApprovedCourseTeaching.semester: (fields.W122) 'max_length' is ignored when used with IntegerField
    HINT: Remove 'max_length' from field
collection.Profile.level: (fields.W122) 'max_length' is ignored when used with IntegerField
    HINT: Remove 'max_length' from field
collection.ProposedCourseList.level_0_sign: (fields.W122) 'max_length' is ignored when used with IntegerField
    HINT: Remove 'max_length' from field
collection.ProposedCourseList.level_1_sign: (fields.W122) 'max_length' is ignored when used with IntegerField
    HINT: Remove 'max_length' from field
collection.ProposedCourseList.level_2_sign: (fields.W122) 'max_length' is ignored when used with IntegerField
    HINT: Remove 'max_length' from field
collection.ProposedCourseTeaching.level_0_sign: (fields.W122) 'max_length' is ignored when used with IntegerField
    HINT: Remove 'max_length' from field
collection.ProposedCourseTeaching.level_1_sign: (fields.W122) 'max_length' is ignored when used with IntegerField
    HINT: Remove 'max_length' from field
collection.ProposedCourseTeaching.level_2_sign: (fields.W122) 'max_length' is ignored when used with IntegerField
    HINT: Remove 'max_length' from field
collection.ProposedCourseTeaching.semester: (fields.W122) 'max_length' is ignored when used with IntegerField
    HINT: Remove 'max_length' from field

**Comment by Lightyagami1** [comment]
should we use small int fields for optimisation?

**Comment by Lightyagami1** [comment]
level_0_sign = models.IntegerField(max_length=1)
level_1_sign = models.IntegerField(max_length=1)
level_2_sign = models.IntegerField(max_length=1)

for these tags i think usage of boolean field will be better

**Comment by shashi1920** [comment]
'max_length' is ignored when used with IntegerField I didn't have error like this.

anyways we can use boolean too. 

There is lot of change in Structure, as Senthil Sir Explained me, It has become more complicated. and deadline is till 30th July. Anyone in campus ?

**Comment by Lightyagami1** [comment]
A field to store raw binary data. It only supports bytes assignment. Be aware that this field has limited functionality. For example, it is not possible to filter a queryset on a BinaryField value.

this is from django docs , i guess main purpose of these fields will be for filter only. 
Sorry sir for trouble

**Comment by Lightyagami1** [comment]
from --->>  https://docs.djangoproject.com/en/1.8/ref/checks/
under fields sub heading
fields.W122: max_length is ignored when used with IntegerField.

**Comment by shashi1920** [comment]
Okay. thanks for putting this into light. Don't worry I will handle it.
Database needs to be redesign .. a more completed system. I will inform you
by tomorrow afternoon.

**Comment by shashi1920** [comment]
*complicated

On Wed, Jun 17, 2015 at 8:47 PM, Shashikant Sharma IDD M Tech Computer Sc &
Engg., IIT(BHU), Varanasi (U.P.) shashikant.sharma.cse12@iitbhu.ac.in
wrote:
